#!/bin/bash

echo "Setting up the project requirements"
chmod +x bin/setup
bin/setup

echo "Running the project"
docker run \
  --rm \
  -it \
  -w /app \
  -v $(pwd):/app \
  --network=rebase-network \
  -p 3000:3000 \
  ruby \
  bash -c "chmod +x scripts/install_gems && sh scripts/install_gems && RACK_ENV=development ruby server.rb"
